// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/memorizer-screens/Deadline.tsx": () => import("../components/mockups/memorizer-screens/Deadline.tsx"),
  "./components/mockups/memorizer-screens/FlowBoard.tsx": () => import("../components/mockups/memorizer-screens/FlowBoard.tsx"),
  "./components/mockups/memorizer-screens/Home.tsx": () => import("../components/mockups/memorizer-screens/Home.tsx"),
  "./components/mockups/memorizer-screens/HomeEmpty.tsx": () => import("../components/mockups/memorizer-screens/HomeEmpty.tsx"),
  "./components/mockups/memorizer-screens/Input.tsx": () => import("../components/mockups/memorizer-screens/Input.tsx"),
  "./components/mockups/memorizer-screens/MnemonicDisplay.tsx": () => import("../components/mockups/memorizer-screens/MnemonicDisplay.tsx"),
  "./components/mockups/memorizer-screens/Practice.tsx": () => import("../components/mockups/memorizer-screens/Practice.tsx"),
  "./components/mockups/memorizer-screens/PracticeFlow.tsx": () => import("../components/mockups/memorizer-screens/PracticeFlow.tsx"),
  "./components/mockups/memorizer-screens/Results.tsx": () => import("../components/mockups/memorizer-screens/Results.tsx"),
  "./components/mockups/memorizer-screens/Settings.tsx": () => import("../components/mockups/memorizer-screens/Settings.tsx"),
  "./components/mockups/memorizer-screens/Splash.tsx": () => import("../components/mockups/memorizer-screens/Splash.tsx"),
  "./components/mockups/memorizer-screens/TextDetail.tsx": () => import("../components/mockups/memorizer-screens/TextDetail.tsx"),
  "./components/mockups/pitch-title/ProductSplit.tsx": () => import("../components/mockups/pitch-title/ProductSplit.tsx"),
  "./components/mockups/memorizer-screens/data/DataContext.tsx": () => import("../components/mockups/memorizer-screens/data/DataContext.tsx")
};
